version: '3.9'

services:
  gatsby:
    build:
      context: .
      dockerfile: ./.docker/gatsby/Dockerfile
    container_name: arsaga-hackathon-website-gatsby
    working_dir: /arsaga-hackathon-website
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - .:/arsaga-hackathon-website
      - ~/.ssh:/root/.ssh
    stdin_open: true
    tty: true
