version: 2.1

#  実行環境を定義
executors:
  node:
    docker:
      - image: circleci/node:16.13.1

jobs:
  build:
    executor:
      name: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - gatsby-npm-{{ checksum "package-lock.json" }}
            - gatsby-npm-
      - run:
          name: 'npm install'
          command: npm install
      - save_cache:
          key: gatsby-npm-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - unless:
          condition:
            equal: ['master', <<pipeline.git.branch>>]
          steps:
            - run:
                name: 'delete SEO files'
                command: rm -f ./static/robots.txt ./static/sitemap.xml
            - run:
                name: 'create robots.txt'
                command: "echo 'User-agent: *\nDisallow: /' > ./static/robots.txt"
      - run:
          name: 'build'
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor:
      name: node
    steps:
      - attach_workspace:
          at: .
      - when:
          condition:
            equal: ['master', <<pipeline.git.branch>>]
          steps:
            - run:
                name: 'deploy production'
                command: ./node_modules/.bin/netlify deploy -p -d ./public -a ${NETLIFY_PERSONAL_ACCESS_TOKEN} -s ${NETLIFY_SITE_ID}
      - when:
          condition:
            equal: ['develop', <<pipeline.git.branch>>]
          steps:
            - run:
                name: 'deploy develop'
                command: ./node_modules/.bin/netlify deploy -d ./public -a ${NETLIFY_PERSONAL_ACCESS_TOKEN} -s ${NETLIFY_SITE_ID_DEV}

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
